### ISSUE TITLE
全体的に不要なフラグメント<></>がある

### ISSUE THREAD

**Issue by reachscript-jak** [Mackie-S/raisetech_react#1]
以下の箇所で記載しているフラグメントは無くて大丈夫かと思います！
あくまで、複数のタグが並列していてエラーを回避する時のみ使用すると良いかと思います👍

https://github.com/Mackie-S/raisetech_react/blob/4dac30f0658d62fbd40a761d265a809de5b01bd0/src/App.jsx#L21-L22

https://github.com/Mackie-S/raisetech_react/blob/4dac30f0658d62fbd40a761d265a809de5b01bd0/src/Components/QuizLists.jsx#L38-L39

https://github.com/Mackie-S/raisetech_react/blob/4dac30f0658d62fbd40a761d265a809de5b01bd0/src/Components/Questions.jsx#L51-L52

**Comment by Mackie-S** [comment]
上記不要なフラグメントを削除。
また、空のフラグメントが必要だった箇所もじゃけぇさんより別のスマートな記述を教えてもらい変更。
