### ISSUE TITLE
タブを変えると画面の状態がリセットしてしまう件について

### ISSUE THREAD

**Issue by mizushima1226** [Mackie-S/raisetech_react#10]
> 画面下部の「正答を表示する」ボタンを押すとそれぞれの問題の下に正解or不正解が出るのですが、
        タブを変えるとリセットしてしまう
        [試したこと]
        見当がついていないので試せていないのですが、ブラウザストレージを利用するなどでしょうか？
　　（こうすると「やり直す」ボタンでリロードした際にもやり直せないのでどうなのか？と思ってます。。）

実装が複雑になってきているのでtry&errorな作業イメージでコメントします！↓

ラジオボタンのステータス制御を`RadioShowAnswers`でおこなっているのが気になりました
`categories`のステートで「どれを選択したか？」のステートも管理すると解消されるかもしれません🤔

ここら辺、今のコードに変更を加えるのもOKですが、変更自体が複雑になりそうなので、
一旦今回の現象が再現するような単純なサンプルコードを[codesandbox](https://codesandbox.io/dashboard/recent)などで作って検証してみるのもいいかもしれません。。。
（お任せします！）

あ、https://headlessui.dev/react/tabs のサンプルコード引用された感じですかね👀
確かにサンプルの方でも同様の現象再現してますね
こちらのサンプルで選択した項目のリセットされないような実装を考えて、今作成中のアプリにフィードバックするのがコスパ良くtry&error繰り返せる気がします〜

**Comment by Mackie-S** [comment]
色々と試行錯誤したのですが手詰まりになったのでヒントをいただきたいです。。

### **考えたこと**

1. EachQuizTabs.jsxの `<Tab.Group>` のonChangeで「タブを移動したときに**選択されているという状態を保持する記述**」をする必要がある
2. 現在の実装では、選択されている状態を管理しているのはRadioShowAnswers.jsxの`const [selected, setSelected] = useState("");`なのでこの部分を`EachQuizTabs`からpropsを受け取っての実装になる

### **試したこと**

> categoriesのステートで「どれを選択したか？」のステートも管理すると解消されるかもしれません🤔

- ということでしたので`SelectedAnser: "" ;` というkey, valueをcategoriesに追加し、`const [selected, setSelected] = useState(props.SelectedAnswer);` にしてみました
- stateが更新された後にcheckedになっているAnswerを取得し、それを保持するという記述がわかリませんでした
　→https://teratail.com/questions/349681 の
` const inputAnswer = (selectedAnswer, targetIndex) => {
    setqLists(qLIsts.map((list, index) => (index === targetIndex ? { ...list, selectedAnswer } : list)))
  } ` という記述が一番求めているものに近いと思いますが、今回の仕様でどのように組み合わせられるかの検討がつきませんでした

- またググりまくって辿り着いたのが`sessionStorage.setItem` で、
`<RadioGroup value={selected} onChange={( ) => setSelected(sessionStorage.setItem("example", Answer))}` としてみましたがうまく実装できませんでした

### **気になること**

- そもそもmap()でreturnしている箇所（今回で言うと下記の箇所）
https://github.com/Mackie-S/raisetech_react/blob/08e5be9f754274726bc2139648c6e003ffab8008/src/Components/RadioShowAnswers.jsx#L19-L28
この箇所の定数をmapで処理する前に使用することはできないと思うのですが、その場合の処理は一々mapの記述を書いた上で定数宣言をしなければならないのでしょうか？
上記の例で言えば19行目で`props.Answers.map((Answer) ・・・)`としていますが、map処理する前の1 ~ 18行の部分ではprops.Answersは使えてもAnswerを単体で使うことはできないはずです。
1 ~ 18行の部分でAnswerを使いたい場合は面倒でも毎回` props.Answers.map((Answer) ・・・) ` を使用しないと行けないのでしょうか？

中々文章で伝えるのが難しいのですが、上記ご確認お願いいたします！

**Comment by mizushima1226** [comment]
```
 Reactクイズ: [
      {
        id: 1,
        Question: "Reactを開発したのは誰？",
        Answers: ["Twitter", "Facebook", "mixi", "Brendan Eich"],
        Correct: "Facebook",
        Group: "React",
        selected: "",
      },
```

`selected`を追加した、であってますよね👀
Goodだと思います👍

`RadioShowAnswers`側で
```
const [selected, setSelected] = useState("");
```
とステートを定義していますが、これは不要で、追加した`selected`をpropsとして受け取る必要があります

以下のように実装すると、selectedの値で選択され、タブ移動してもステートが保持されているため、選択が外れないです
classNameで受け取れる`active/checked`は使用しません（選択したかどうか？はステートで管理するため）

```
Reactクイズ: [
      {
        id: 1,
        Question: "Reactを開発したのは誰？",
        Answers: ["Twitter", "Facebook", "mixi", "Brendan Eich"],
        Correct: "Facebook",
        Group: "React",
        selected: "Twitter",
      },


 <RadioGroup.Option
                key={Answer}
                checked={Answer === selected}
                value={Answer}
                className={`${Answer === selected ? "ring-2 ring-white ring-opacity-60 ring-offset-2 ring-offset-sky-300" : ""}
                ${Answer === selected ? "bg-sky-900 bg-opacity-75 text-white" : "bg-white"}
                  relative flex cursor-pointer rounded-lg px-5 py-4 shadow-md focus:outline-none`}
              >
```

あとは
```
<RadioGroup value={selected} onChange={(value) => console.log(value)}>
```
で選択した値が取得できるので、どのようにステートを更新するか？を考えて実装する必要がありますね🤔

ここら辺の実装は仰る通り、
```
const inputAnswer = (selectedAnswer, targetIndex) => { setqLists(qLIsts.map((list, index) => (index === targetIndex ? { ...list, selectedAnswer } : list))) }
```
と似たような実装になるかもしれません

**Comment by Mackie-S** [comment]
`<RadioGroup value={selected} onChange={(value) => console.log(value)}>`

直近リプライの上から順に上記箇所までは順調に行きましたが、

`const inputAnswer = (selectedAnswer, targetIndex) => { setqLists(qLIsts.map((list, index) => (index === targetIndex ? { ...list, selectedAnswer } : list))) }`

こちらの実装がうまくいかない日々ですね。。

###  **とりあえず試して見たこと**
EachQuizTabs.jsx内に下記のように記述してみました。

```
{EachQuizTabs.jsx}

  const [categories,setCategories] = useState({
    Reactクイズ: [
      {
        id: 1,
        Question: "Reactを開発したのは誰？",
        Answers: ["Twitter", "Facebook", "mixi", "Brendan Eich"],
        Correct: "Facebook",
        Group: "React",
        SelectedAnswer: "",
      },
      ・
      ・
      ・

const inputAnswer = (value) => {
  setCategories(Object.values(categories).map((posts) => {
    return (
      posts.map((post) => {
        return (
            post.SelectedAnswer = value
          )
        })
      )
    }))
  }
```

やりたいこととしては
`SelectedAnswer: ""`
の箇所を
`SelectedAnswer: value`
のように４択のうちのいずれかを選んだらその値に更新したいと思ってます。

しかし

```
{RadioShowAnswers.jsx}

        <RadioGroup value={props.SelectedAnswer} onChange={props.inputAnswer(value)}>
```
のように記述してもうまくいきませんでした。

自分の理解不足、とりわけJSに対しての理解不足なのか、以前仰っていたように仕様・設計の問題で複雑になってしまっていることが原因でうまくいっていないのかがわからないのですがいかがでしょうか？

もし後者の仕様・設計の見直し絡みでしたらこちらもスキップしようかとも考えています。
（実際の現場では仕様・設計を見直すことでもっと楽に実装できるのであれば今力技で乗り切ってもどうかと思っているので）

前者の理解不足の場合はどの部分の学習をすればよいかご指導いただけますでしょうか？

ご確認よろしくお願いいたします！

**Comment by mizushima1226** [comment]
どうロジックを組んで実装するか？といったところだと思います〜
仕様や設計をブラッシュアップしても、ここのロジックと実装はそんなに変わらないところかと💡
（自分でもこのクイズアプリ少し実装してみましたが、今取り掛かっていらっしゃる箇所と似たような場面がありました👍）

`setCategories`を実行している箇所ですが、狙った値で更新できているか確認できてますでしょうか？
自分はよく以下のような感じで確認しています〜

```
const inputAnswer = (value) => {
  const newCategories = Object.values...
  console.log(newCategories);
  setCategories(newCategories);
  }
```

また以下のようなイメージだと思います
```
// 更新前
Reactクイズ: [
      {
        id: 1,
        Question: "Reactを開発したのは誰？",
        Answers: ["Twitter", "Facebook", "mixi", "Brendan Eich"],
        Correct: "Facebook",
        Group: "React",
        SelectedAnswer: "",
      },

// 更新後
Reactクイズ: [
      {
        id: 1,
        Question: "Reactを開発したのは誰？",
        Answers: ["Twitter", "Facebook", "mixi", "Brendan Eich"],
        Correct: "Facebook",
        Group: "React",
        SelectedAnswer: <ここに選択した値が設定される>,
      },
```

現状、`inputAnswer`には`value`の引数のみを与えていますが、
やりたいことは「Reactクイズの１つ目の問題の`SelectedAnswer`を`value`で更新する」といった処理なので引数が足りなそうです🤔

**Comment by Mackie-S** [comment]
毎度、早速のリプライありがとうございます🙇‍♂️

教えていただいたものを参考にdevelop branchに下記のように実装しております。

https://github.com/Mackie-S/raisetech_react/blob/00b6e00ff24d7b1a6c0fa211a4b3bec28e874e37/src/Components/EachQuizTabs.jsx#L82-L94

https://github.com/Mackie-S/raisetech_react/blob/00b6e00ff24d7b1a6c0fa211a4b3bec28e874e37/src/Components/RadioShowAnswers.jsx#L11

このようにすることで分かったこととしてはReactクイズ、スーパー戦隊クイズ、香料クイズなどのObject.key部分の名前がindex番号に変更されてることがわかりました。

```
onChange前

Reactクイズ: [...],
スーパー戦隊クイズ:[...],
香料クイズ:[...]

onChange後

0:[...]
1:[...]
2:[...]

```

これはどこをクリックしても起こきてしまいます。

ロジックとしては
押した箇所のクイズのindexを取得し、そのindex内のSelectedAnswerの値をValueにすること
だと思うのですが、その構文を実装するのが難しいですね。。

下記スクショのようにpostはこのようなobjectとして認識されてるようです。
<img width="333" alt="スクリーンショット 2022-06-29 10 02 20" src="https://user-images.githubusercontent.com/92088651/176329060-3739a627-9fa4-49f9-ab18-bb01e8616d93.png">

なので下記のように関数の記述を変更してみましたがエラーが出てしまいます。

```
  const inputAnswer = (SelectedAnswer, targetIndex) => {
    const newCategories = Object.values(categories).map((posts) => {
    return (
      posts.map((post, index) => {
        return (
          // post.SelectedAnswer:SelectedAnserの部分でエラーが出る
          index === targetIndex ? { ...post, post.SelectedAnswer:SelectedAnswer } : post
          )　
        })
      )
    })
    console.log(newCategories);
    setCategories(newCategories);
  }
```

もう一息だと思ってはいますがアドバイスいただけますでしょうか？

**Comment by mizushima1226** [comment]
これあれですね。。。
`categories`は元々Object型なのでkey-valueのペアでしたね。。。
それに対してArray.mapで配列を生成してしまっているので、そもそも作りたいデータの型が間違っている状態になっています👀

新しい配列ではなく、新しいObjectを作成したいので、以下の実装イメージになるかと思います

```
const newCategories = {};

Object.values(categories).forEach((posts) => {
  // 何か処理処理
  // newCategoriesにkey-valueのペアを追加
}

```

参考： https://qiita.com/chihiro/items/eb8c7b2ceee5274a4a8f

**Comment by Mackie-S** [comment]
あと一息かと思っております。

https://github.com/Mackie-S/raisetech_react/blob/ac447e2e2edd2ae55ca735dfe37e418b7d9782af/src/Components/EachQuizTabs.jsx#L92-L99

こちらの記述を画面で確認するとSelectedAnswerが変更されており、一歩前進した感じがしております！

あとはこのpost.Answers[0]の部分を押下した部分にしたいのですが、色々検討してみてもわからなかったです。。

あと
`const newCategories = {};`
で空の配列を用意した後
`Object.values(...`
の中で使用するとエラーが出るのですがletを使用すべきところでしょうか？
いずれにせようまくロジックを組めなかったので一旦上記のような記述で進めておりました。

そろそろ先に進みたいですね。。
他にも学ぶ必要が山ほどある中でこの部分だけでこれだけ時間を費やすのはどうだろうと思い始めております。
人生を変えたい野望があるので挫折はしないつもりですが中々しんどい日々です。
答えを教えてもらいたい気持ちもありますが、せめてもう少し詳細なヒントをいただけないでしょうか？

文章でこのようにやりとりするとどうしても詳細を伝えるのが難しいですし、時間がかかりすぎてしまいます。。

**Comment by mizushima1226** [comment]
>Object.values(...
の中で使用するとエラーが出るのですがletを使用すべきところでしょうか？

どのようなエラー文でしたでしょうか？


今の実装だと、全ての`SelectedAnswer`を更新しようとしているような実装に見えます🤔

>やりたいことは「Reactクイズの１つ目の問題のSelectedAnswerをvalueで更新する」といった処理なので引数が足りなそうです🤔

これに従ってより詳細な`inputAnswer`の実装イメージは
```
const inputAnswer = (key, quizIndex, answerValue) => {
  const newCategories = // 現在のcategoriesのコピーを作成する
  
  // 引数のkeyをもとに、categoriesから対象のクイズ種別を取得する（Reactクイズ）
  const target = 

  // targetから特定のクイズを取得する（Reactを開発したのは誰？）のオブジェクト
  const quiz = 

  // quizのSelectedAnswerにanswerValueを設定する
}

inputAnswer("Reactクイズ", 0, "Twitter");  // 0は「0番目の問題」
```
のような感じになるかと
ここではforEachなど具体的な処理は書いてませんがforEach使っても実装できますし、使わない実装方法もあるかと思います
（ロジック書くときは↑のようにまずは日本語で処理フローを言語化すると良いです💡）

だいぶ苦戦しているので思い切って実装方針変えてもいいかもしれません

>他にも学ぶ必要が山ほどある中でこの部分だけでこれだけ時間を費やすのはどうだろうと思い始めております。

少し焦る気持ちがあるなら一旦先に進んでみてもいいと思いますよ！！👍
ずっと１つの課題に取り組み続けるのも辛いし面白味も薄れていくと思うので！！

先の課題を進めつつ、今の課題の時間も少しだけ確保する、もしくは課題を進めていく中で実装力つけてからこの課題に再チャレンジするとかでもありだと思います

**Comment by Mackie-S** [comment]
ご無沙汰しております！
返事がすっかり遅くなってしまって申し訳ありません。
おっしゃるように他の箇所の学習、とりわけJSの学習に時間を割いておりました。

その甲斐あって

```
const inputAnswer = (key, quizIndex, answerValue) => {
  const newCategories = // 現在のcategoriesのコピーを作成する
  
  // 引数のkeyをもとに、categoriesから対象のクイズ種別を取得する（Reactクイズ）
  const target = 

  // targetから特定のクイズを取得する（Reactを開発したのは誰？）のオブジェクト
  const quiz = 

  // quizのSelectedAnswerにanswerValueを設定する
}

inputAnswer("Reactクイズ", 0, "Twitter");  // 0は「0番目の問題」

```

の部分は実装することができました！
https://github.com/Mackie-S/raisetech_react/blob/03f91d1331f31b0fc50a8b8c711255c303af362e/src/Components/EachQuizTabs.jsx#L91-L125


しかしまた躓きポイントがあるのでアドバイスをいただきたく。。
quizのSelectedAnswerにanswerValueを設定したのは良いですが、それを最後にnewCategoriesに反映しなければならないと思います。
現在はfilter()などで新しい配列を生成しながら中身にアクセスしているため、元のnewCategoriesの値は変更されておりません。
分割代入やスプレッド構文を駆使すればこの変更ができるのでしょうか？
ググってもこの部分がわからなかったのでどのようにすべきかアドバイスいただけますでしょうか？

**Comment by Mackie-S** [comment]
解決しました！
こちらの第二引数を1にしていたので正しく反映されておりませんでした。正しくは０ですね。
（色々いじくってコンソールで確認していたのですが元に戻し忘れてました）
https://github.com/Mackie-S/raisetech_react/blob/03f91d1331f31b0fc50a8b8c711255c303af362e/src/Components/EachQuizTabs.jsx#L123-L125

オブジェクトの中にあるオブジェクトや配列はスプレッド構文でもシャローコピーなので値が変更されたら大元も変更されるわけですね！

あとはRadioShowAnswers.jsxnのonChangeをどのように変更するか、検討します！

**Comment by mizushima1226** [comment]
> の部分は実装することができました！

素晴らしいです〜🙌

> 解決しました！
こちらの第二引数を1にしていたので正しく反映されておりませんでした。正しくは０ですね。
（色々いじくってコンソールで確認していたのですが元に戻し忘れてました）

こちらもナイス自己解決です👍
個人的な感覚ですが、console.logでどれだけ粘り強くデバッグしているかが今後の成長の伸びにつながってくるかと思っています

あともう一踏ん張りですね〜🚀🚀🚀

**Comment by Mackie-S** [comment]
`inputAnswer(key,quizIndex,targetValue)` の第一引数であるkeyには現在表示されているタブ（Reactクイズ、スーパー戦隊クイズ、香料クイズのいずれか）が入ります。
つまり
https://github.com/Mackie-S/raisetech_react/blob/d43135eb1210cf1e9915050ff4ff8e4f96159ae6/src/Components/EachQuizTabs.jsx#L125-L130
の箇所でループしているcategoryを拾ってくる必要があると思います。
しかしRadioShowAnswers.jsxはこの箇所の子コンポーネントではないのでcategoryをpropsとして受け取ることができません。

この場合の対応をググっても検討がつかなかったのですが何かアドバイスをいただけないでしょうか？

**Comment by mizushima1226** [comment]
なるほどです〜

https://github.com/Mackie-S/raisetech_react/blob/d43135eb1210cf1e9915050ff4ff8e4f96159ae6/src/Components/EachQuizTabs.jsx#L134

ここでObject.Values使っているので値のリストしか取れていないようですね👀
Object.KeysやObject.entriesなど使えばkeyが取れるのでいけそうです💡

**Comment by Mackie-S** [comment]
おかげさまで本issueの機能を実装できました！！！

両方欲しい時はObject.entriesを使ってprops渡し用のみに利用すれば良いんですね。
勉強になりました。

これだけでなく色々と勉強になりました。
６月いっぱい育休を取ってたのでがっつり進めようと思っていたのに思うように進まず辛かったですが、途中でJSの基礎を学ぶという方向に向かえて最終的に乗り越えられて良かったです。

今回学んだことは初学者の躓きポイントとしてQiitaなりにまとめてみようと思います！

長々とお付き合いいただき本当にありがとうございました！！
よろしければcloseにします。

**Comment by mizushima1226** [comment]
お疲れ様です！！🎉🎉🎉🎉🎉🎉🎉

>６月いっぱい育休を取ってたのでがっつり進めようと思っていたのに思うように進まず辛かったですが、途中でJSの基礎を学ぶという方向に向かえて最終的に乗り越えられて良かったです。

ナイス踏ん張りです〜🙌
まさか前半戦のアウトプットでここまで密度の濃いものになるとは想像できなかったです〜

やはり自分で考えたオリジナルのアプリを作るとなると超える壁も必然的に高くなるので良いですね👀

Qiitaでのまとめもめちゃくちゃ良いと思います👍

このissueはcloseでOKです〜
![LGTM](https://image.lgtmoon.dev/171840)
