### ISSUE TITLE
正解ボタンで正解を表示するとタブを切り替えても正解が表示されてしまう

### ISSUE THREAD

**Issue by mizushima1226** [Mackie-S/raisetech_react#11]
>  一つ目のタブで正答を表示してしまうと、別のタブに移動して回答を選択したら
        正答表示ボタンを押さずとも正答が表示されてしまう
        [試したこと]
　　こちらも見当がついていないので試せておりません。
　　「タブを移動する」という挙動を記述できればif文等で実装できそうだとは思いますが、その記述がわからないです。。

３つのタブに対し、１つの「正解表示」ボタンでやりくりしているからだと思います👀
以下の対応案がパッと浮かびました🤔

案１
３つのタブの中にそれぞれ「正解表示」ボタンを設置して区別する

案２
１つの「正解表示」ボタンでやりくりする。タブを切り替えるときにボタンの状態をリセットする

**Comment by Mackie-S** [comment]
案１、２両方トライしてみましたが、案２の方が実装しやすかったのでそちらで実装しました！

https://github.com/Mackie-S/raisetech_react/blob/d18a246c08dc3484ce044ef70ed444eaf46cbc52/src/Components/EachQuizTabs.jsx#L17-L19

https://github.com/Mackie-S/raisetech_react/blob/d18a246c08dc3484ce044ef70ed444eaf46cbc52/src/Components/EachQuizTabs.jsx#L74

を記述して実装できましたのでご確認お願いいたします🙂

**Comment by mizushima1226** [comment]
動作確認できました〜
動きとしてはOKと思います👍

実装ですが、以下の感じがシンプルで良いかと！
単純に、「表示する処理」「非表示にする処理」といった感じです〜
```
const onClickshow = () => {
    setIsShowAnswers(true);
  };
  const onChangeMoveTab = () => {
    setIsShowAnswers(false);
  };
```

**Comment by Mackie-S** [comment]
ご確認ありがとうございます！
なるほど。
確かにその方が目的の実装ができますね。
そちらに変更してこちらのissueはクローズします🙋‍♂️
