### ISSUE TITLE
コンポーネント名とファイル名は統一すると可読性が良い＆import時の拡張子は不要

### ISSUE THREAD

**Issue by reachscript-jak** [Mackie-S/raisetech_react#2]
- exportしているコンポーネント名とファイル名が異なっていますが、１つのファイルから１つのコンポーネントをexportしている場合は名称を統一したほうが混乱しないかと思います！

- import 時に.jsxまで記載していますが拡張子は書かなくてもimportできるので一般的には記載しないです

https://github.com/Mackie-S/raisetech_react/blob/4dac30f0658d62fbd40a761d265a809de5b01bd0/src/App.jsx#L3

**Comment by Mackie-S** [comment]
ファイル名を変更し、App.jsxのimportも変更
