### ISSUE TITLE
Props名、変数名はキャメルケースが一般的

### ISSUE THREAD

**Issue by reachscript-jak** [Mackie-S/raisetech_react#3]
Props名はキャメルケースを一般的に用います！（先頭が小文字で単語の区切りが大文字）
また、変数名もJavaScriptではキャメルケースが一般的かなと思います👍
（例: questionLists、reactQuizLists、superHeroQuizLists）

https://github.com/Mackie-S/raisetech_react/blob/4dac30f0658d62fbd40a761d265a809de5b01bd0/src/Components/QuizLists.jsx#L40

**Comment by Mackie-S** [comment]
props名と変数名をパスカルケースからキャメルケースに変更
