### ISSUE TITLE
QuestionsコンポーネントへのPropsの渡し方について

### ISSUE THREAD

**Issue by reachscript-jak** [Mackie-S/raisetech_react#4]
複数の配列をまとめて特定のコンポーネントにPropsに渡す手法としては記述いただいている内容でgoodです！👍

（今回の場合はただの定数なのでPropsで渡す必要がありませんが...コメントに書かれている通り本来のアプリであればクイズの内容等はDBに保持するかと思います）

Propsやコンポーネント化の練習という意味では良いかと思いますが、今回の場合、Quizzesコンポーネントが存在する意味があまりないというのはあります👀

よくあるやり方としては「一覧用のコンポーネント」と「一覧に表示する各要素のコンポーネント」に分ける方法です。

一例）
QuizLists.jsx
```
export const Quizzes = () => {
  const questionLists = [...ReactQuizLists, ...SuperHeroQuizLists];
  return (
    <div>
      {questionLists.map((question) => <Questions question={question}/>)}
    </div>
  );
};
```

として
Questions.jsxは１つのクイズの情報を表示するようにするイメージです👌

**Comment by Mackie-S** [comment]
https://github.com/Mackie-S/raisetech_react/issues/5#issue-1231940923
こちらでコメントしておりますが、ライブラリを使用することで構造を変更したのでこちらのissueはクローズとします。

ご説明ありがとうございました！！
