### ISSUE TITLE
Questions.jsxの記述が長くなってきている問題について

### ISSUE THREAD

**Issue by reachscript-jak** [Mackie-S/raisetech_react#5]
コンポーネント化の仕方を改善するとよさそうです！

今はほとんどのロジックをQuestions.jsxが持っており、画面としてのコンポーネントの役割を担っている感じになっています。

コンポーネント化の方向性の一例として

- 画面のコンポーネント
  - クイズ一覧用のコンポーネント（※なくても可）
    - 各クイズのコンポーネント

とすることを考え、

- 画面のコンポーネント
  - クイズを始める、やり直す、集計するボタンやその押下処理
  - 正解数の表示
  - どの選択肢が選ばれているかのstate 等をもたせる（onChange関数を各クイズのコンポーネントにPropsとして渡す）

- 各クイズのコンポーネント
  - 選択肢のUIや、Propsで受け取ったonChangeの実行、集計実行時の正解の情報等の表示

のようにしていくとスッキリするかと思います！

このあたり慣れも必要なのでまた分からなければ聞いてください👍

**Comment by Mackie-S** [comment]
大分時間がかかってしまいましたがHeadless UI のRadio GroupとTabsを導入して抜本的に構造を変えてみました！

もう少しコンポーネントを分割した方が良い等ございましたらご指摘いただきたいです🙇‍♂️

**Comment by reachscript-jak** [comment]
@Mackie-S 
以前に比べかなり良くなったと思います！👏
コンポーネント名はMy〜のような命名は実際にはしないので、しっかりそのコンポーネントの役割を表すようにすると良いかと思います👍

例えばMyRadioは現状単なるラジオボタンではなく、クイズの複数の選択肢や結果を表示しているので命名の工夫をするともっと読む側にわかりやすいですし、MyTabsも工夫できそうです👌

一旦このissueとしてはcloseで良いかと思います！👍

**Comment by Mackie-S** [comment]
@reachscript-jak 
早速ご確認ありがとうございます！
コードも然り相手に分かりやすい記述を意識して作っていきたいと思います✋
自分なりにリネームしてみましたのでcloseします！
