### ISSUE TITLE
ラジオボタンのonClickについて

### ISSUE THREAD

**Issue by reachscript-jak** [Mackie-S/raisetech_react#6]
ラジオボタンの選択肢を変更する際は一般的にonChangeイベントが用いられるので試してみてください👍

https://github.com/Mackie-S/raisetech_react/blob/4dac30f0658d62fbd40a761d265a809de5b01bd0/src/Components/Questions.jsx#L38

**Comment by Mackie-S** [comment]
onChangeに変更し、下記サイトでその他のonイベントについても確認しました！
https://phpjavascriptroom.com/?t=js&p=event
