### ISSUE TITLE
isShowの命名について

### ISSUE THREAD

**Issue by reachscript-jak** [Mackie-S/raisetech_react#7]
いくつかisShowというStateがありますが、実際のアプリでは変数名からすぐ意味が分かるのが理想なので、

`isShowCorrectAnswers` のように明示的に変数名をつけてあげたほうが良いかと思います👍

**Comment by Mackie-S** [comment]
二箇所に使用していたため下記のよな名称に変更しました！
https://github.com/Mackie-S/raisetech_react/blob/bf70c1706cdcc5375d5e05f72c24497eec878abb/src/Components/Questions.jsx#L4-L7
