### ISSUE TITLE
未回答の問題があるとき、アラートを表示したい件について

### ISSUE THREAD

**Issue by mizushima1226** [Mackie-S/raisetech_react#9]
> 未回答の問題がある場合にtoastでアラートを出したい
　　[試したこと]
　　src/Components/RequiredAleart.jsx　にて記述している内容をsrc/Components/MyTabs.jsx の
　　103行目の<Buttons>コンポーネントに置き換えてpropsを渡しておりましたがうまくいきませんでした。

ソースコードを確認すると、アラートを表示する処理が記述されていないように見えますが、私が見てる箇所あってますでしょうか？
`src/Components/MyTabs.jsx`は存在しないファイルのようでして。。。

https://github.com/Mackie-S/raisetech_react/blob/ba0a2083b685f1b1c6edfcb9c38e9ce018f225cd/src/Components/EachQuizTabs.jsx#L14-L16

**Comment by Mackie-S** [comment]
すみません、MyTabs.jsxからEachQuizTabs.jsxにリネームしておりました。。

そしてアラート表示の記述も一旦削除しており、大枠の機能が使える状態にしておりました。
つまりRequiredAleart.jsxは存在するが使用されていない状態ということです。。

こちらで説明しますと、下記関数の箇所がうまく機能していないことが原因かと思ってまして、
`props.category.checked`というpropsの受け取り方が不十分かと思っております。

https://github.com/Mackie-S/raisetech_react/blob/f36bef6cfa16556097a3333eaa23ba475921be86/src/Components/RequiredAleart.jsx#L6-L12

EachQuizTabs.jsxにあるcategoriesというオブジェクトのReactクイズ、スーパー戦隊クイズ、香料クイズのそれぞれのグループの全ての回答をcheckedの状態にしていないとアラートが出るという記述をしたいと思ってますが、これをどう記述するのかがわからない状態ですね😓
https://github.com/Mackie-S/raisetech_react/blob/f36bef6cfa16556097a3333eaa23ba475921be86/src/Components/EachQuizTabs.jsx#L17-L66

こういう時に使用できるメソッドがあるのでしょうか？
ご確認お願いいたします！

**Comment by mizushima1226** [comment]
>Reactクイズ、スーパー戦隊クイズ、香料クイズのそれぞれのグループの全ての回答をcheckedの状態にしていないとアラートが出るという記述をしたいと思ってますが

であればやはり、何を選択しているか？のステートを管理する必要がありますね👀

---

```
const [categories] = useState({ 
   Reactクイズ: [ 
     { 
       id: 1, 
       Question: "Reactを開発したのは誰？", 
       Answers: ["Twitter", "Facebook", "mixi", "Brendan Eich"], 
       Correct: "Facebook", 
       Group: "React", 
     }, 
```

こちらはクイズを表示する元ネタの情報になっているかと思います
これに加えて、ユーザーが何を選択したか？を保持するプロパティを追加すると良さそうです

---

```
const [categories, setCategories] = useState({})
```
セット関数必要です
ユーザーがラジオボタン押下するとステートを更新する必要あります

---

正解表示ボタンを押下した際に、categoriesに設定されている各回答をチェックし、１つでも未設定の回答があればメッセージを表示、全て設定されていたら正解と照らし合わせる

のようなロジックを実装するイメージです

データ構造が複雑になっているので、厳しそうだったら
- 「Reactクイズ」単体であることを前提にしたデータ構造でロジックを組んでみる
- レビューを受ける→ブラッシュアップする
- 「香料クイズ」など複数対応したデータ構造に拡張して実装してみる

など段階を踏んで進めていくのもありです👌

---

また、仕様と設計もう少し詰めれるかなぁと感じました🤔
１タブで１つのカテゴリに対するクイズが完結しているような画面設計なので、
１タブ内でクイズ機能を完結させるような仕様にしても良いかなぁと
画面設計に対して、実現しようとしていることが、３つのタブをまたぐような仕様になっているので、データ構造や実装がより複雑になっている印象です🤔

**Comment by Mackie-S** [comment]
早速レビューありがとうございます！
みずしまさんから見ても複雑ということで安心しました。笑
この構造の理解にかなりの時間を費やしてしまったのでもっと早くレビューして貰えば良かったと後悔しております。。。
（単純にJSの理解不足なのか？と思っていましたがそもそも複雑だったんですね）

***

```
const [categories] = useState({ 
   Reactクイズ: [ 
     { 
       id: 1, 
       Question: "Reactを開発したのは誰？", 
       Answers: ["Twitter", "Facebook", "mixi", "Brendan Eich"], 
       Correct: "Facebook", 
       Group: "React", 
　　Selected: "",
     }, 
```
こちらのようにSelected: ""のプロパティを追加しようと思います。

***

その他、おっしゃるように複雑で中々実装が難しいので構造を見直してみようと思います！

***

ちなみに

> １タブ内でクイズ機能を完結させるような仕様

というのはmap()で処理する構造を見直すイメージでしょうか？
口頭で説明するのが難しいのですが、正答表示ボタンもそのタブの中に含めて他のタブとは切り離すようなイメージ、
それこそhttps://github.com/Mackie-S/raisetech_react/issues/11#issue-1272973508
の案1のようなイメージでしょうか？

**Comment by mizushima1226** [comment]
>こちらのようにSelected: ""のプロパティを追加しようと思います。

> 複雑で中々実装が難しいので構造を見直してみようと思います！

>というのはmap()で処理する構造を見直すイメージでしょうか？

対応方針によってだいぶ変わってくるかと思います

例えば、
- 仕様を再検討する
- 仕様に基づいて画面設計を見直す
- データモデルを考える
- ロジックを整理する（テキストに書き出せるとベスト）
- 実装する

な開発全体のイメージですね〜

現状だと
- 仕様（抜粋）
  - 全てのタブで回答済みかをチェックしたい
- 画面
  - 各タブでクイズが分かれている
  - タブ１で回答→正解を表示→タブ２で回答→の流れになっている
- 実装
  - categoriesのように全てのクイズが１つにまとまっている

課題感としてはざっくり以下の感じかなぁと
タブ２で未回答のクイズがあり、タブ３で正解表示ボタンを押下した場合、タブ２が未回答であることをタブ３でユーザーに伝えることになるので、ここらへんの違和感を解消できるように仕様を見直すor画面設計を見直す

**Comment by Mackie-S** [comment]
### **現在の仕様について（メインのクイズ部分に関して）**
（単なる思い付きから開発を始めたので詰めきれていないことはご承知おきください）

- 4択クイズ
- 時間と時間によって文言が変わる文章をヘッダーに設置（正直いらない実装ですが、dayjsに慣れるため実装）
- ヘッダーにある「クイズを始める」ボタンでメイン部分にクイズを表示、「やり直す」ボタンでリロード
- ３つのカテゴリのクイズがあり、それぞれのクイズにタブで移動する
- １つのカテゴリにつき２つのクイズを用意
- １つのクイズで１つ解答できるradio buttonスタイルで、正解と思うものを選ぶ
- それぞれのタブに「正答を表示する」ボタンがあり、押下でそれぞれのクイズの正誤が表示される

### **今後の仕様について**
 現在の仕様は基本維持しつつ、改善する箇所は下記

- 正答表示ボタンで正解を表示したのち、タブを切り替えても正解が表示されないようにしたい
　→ https://github.com/Mackie-S/raisetech_react/issues/11#issue-1272973508 にて対応
　→案１「３つのタブの中にそれぞれ「正解表示」ボタンを設置して区別する」で対応したい
- １つ目のタブを完了したら完了しっぱなし（タブを移動しても状態がリセットされない）
　→ https://github.com/Mackie-S/raisetech_react/issues/10#issue-1272972240 にて対応
- 未回答のクイズがある場合はアラートを出す（本issue）

その他以下の場合は仕様を変えるべきかと思っております。

- 実際の現場ではあり得ない仕様かつそれを無理矢理やろうとすると実装がかなり複雑で初学者である私では実装が難しい場合（現場の方も避ける実装など）
　→どちらかというとReactの書き方に慣れ、どのようなコードを書けば機能するのかを知りたい目的で課題に取り組んでおりますが、中々厳しい実装になっている部分があればご指摘願います

### **課題点**

> 実装
> categoriesのように全てのクイズが１つにまとまっている

それぞれのクイズをcategoriesでまとめずに分け、propsとして渡すようにしてみようかと思います。

> 仕様（抜粋）
> 全てのタブで回答済みかをチェックしたい
> 画面
> 各タブでクイズが分かれている
> タブ１で回答→正解を表示→タブ２で回答→の流れになっている

こちらの部分は上記categories分割実装後に今後の仕様に記載のように改善していきたいと思っております。

### **追伸**
まず背景として私は未経験でWPコースを修了し、LPコーディング案件を１件行った程度で、JSについてはjQueryを触っていたぐらいというスキルレベルです。
WPコースの時の課題はググって調べることと講義中の質問でほとんど解決できたので、
今回の課題もなるべく自力で解決したいと考えていた中、だいぶ詰まってしまったため質問をしております。
ちなみに下記サブスクに登録してわからない知識は少しずつインプットしております。
https://www.codegrid.net/

根本的な私の学習方針としてスモールステップで課題に取り掛かって徐々にステップアップしていきたいと思っております。
そんな中、第2回目の課題提出であるこちらに対して

> 仕様を再検討する
> 仕様に基づいて画面設計を見直す
> データモデルを考える
> ロジックを整理する（テキストに書き出せるとベスト）
> 実装する

という馴染みがまだないフローが急に来ると先に進みづらいと感じてしまいました。
仕様、設計、データモデルの正しい組み方を心得ている訳ではありませんし、そもそも今回は第2回の課題の要件を満たしつつReactのコーディングに慣れ、さらに自分が実装したいと思っていることがどのようなコードであればスマートなのかを学ぶ段階だと認識しております。
ですのでここではまず求められた要件をクリアして先の課題に進み、ステップアップしたいと考えております。

今後必要になるフローなのは分かりますが、全てを一度にきっちりやると中々先に進めないと感じております。
ですのでご面倒おかけして申し訳ありませんが私の理解レベルまで落とすべく色々とお伺いしますがよろしくお願いいたします。

ひとまず

> 実装
> categoriesのように全てのクイズが１つにまとまっている
> →それぞれのクイズをcategoriesでまとめずに分け、propsとして渡すようにしてみようかと思います。

の部分をトライしてみようと思います。

上記を加味し、このようにした方が良いなどアドバイスございましたらどうぞよろしくお願いいたします。

**Comment by mizushima1226** [comment]
>単なる思い付きから開発を始めたので

とても良いと思います！
自分なりにアプリを考えてアウトプットしている受講生の方は今までいなかった気がします！

>実際の現場ではあり得ない仕様かつそれを無理矢理やろうとすると実装がかなり複雑で初学者である私では実装が難しい場合（現場の方も避ける実装など）
　→どちらかというとReactの書き方に慣れ、どのようなコードを書けば機能するのかを知りたい目的で課題に取り組んでおりますが、中々厳しい実装になっている部分があればご指摘願います

このissueは「未回答の問題があるとき、アラートを表示したい」という実装面での話から始まっておりますが、
これを解決するためには仕様や設計を見直さないといけないことがわかってきた、というのが現状だと思います

>どちらかというとReactの書き方に慣れ、どのようなコードを書けば機能するのかを知りたい目的で課題に取り組んでおります

この目的でいくと、今話している「仕様や設計の見直し」はスキップして先に進んでも良いかもしれません。。。
ここら辺は今後の課題のTodoアプリの開発などで活かしていただければと思います

> それぞれのクイズをcategoriesでまとめずに分け、propsとして渡すようにしてみようかと思います。

ここ、全然tryしてみてよきと思います！

---

追伸ありがとうございます！
コード読んだときのスキル感と大体同じだったのでよかったです
その上で、これだけのアウトプットできること自体、すごいことだと思っています👍
今までの受講生のレビューしてきた中で、仕様や設計・データモデルなどの深い話まで辿り着くことはなかなかありませんでした

この課題で今１００点満点を目指す必要はないと思うので、あまり気負わずにいていただいてOKです🙆‍♂️
今後の課題を進めていく中で、今回作成しているクイズアプリをバージョンアップしていくイメージでも良いと思っています👍

**Comment by Mackie-S** [comment]
色々とアドバイスありがとうございます！
そのように言っていただけて救われます😭
私の目標はバリバリ開発してバリバリ稼いでいきたいので間違いなく深い話をしていく必要があります。
ですがその前段階で思うようにいかず、もやもやしておりました。。
今後ステップアップしていく上で是非お力添えしていただければ幸いです🙇‍♂️

> この目的でいくと、今話している「仕様や設計の見直し」はスキップして先に進んでも良いかもしれません。。。

今回はそうします！
連日 https://github.com/Mackie-S/raisetech_react/issues/10#issue-1272972240 の実装検討をしていていつになったら終わるのやらという状況だったので今後で意識します。
ですのでやむなしですがこちらのissueはクローズしてアラートの実装は見送ろうと思います。。
（categoriesの分割も見送ります）

そして今一度確認です。
「アラート機能を実装しようとすると今の仕様だと厳しいから見直さなければならない」
という状況ですが、複雑にならないための書き方として課題点から見ると

>  - 仕様（抜粋）
>  全てのタブで回答済みかをチェックしたい

→「実際はこのような仕様にするアプリケーションは少ないのでそういった実装を考えることはない」ということでしょうか？

> - 画面
>  各タブでクイズが分かれている
>  タブ１で回答→正解を表示→タブ２で回答→の流れになっている

→「クイズをタブで分けるようなアプリケーションはあまりない（クイズを分けるとしたらページ遷移で実装する）」ということでしょうか？
 
> - 実装
> categoriesのように全てのクイズが１つにまとまっている

→「実際の現場ではデータベースにリストが保管されるので一概に言えないが、仮にリストを今回のようなオブジェクトや配列で記述する場合でもcategoriesのようなまとめ方は複雑になるのでせめて各クイズの配列を用意して実装することが一般的」ということでしょうか？

以上ご確認お願いいたします🙇‍♂️

**Comment by mizushima1226** [comment]
>私の目標はバリバリ開発してバリバリ稼いでいきたいので間違いなく深い話をしていく必要があります。

明確な目標があると自分としてもレビューし甲斐がありますし熱も入ります🚀
ぜひ細かくアウトプットして細かくフィードバック受け取ってもらえればと思います〜

>→「実際はこのような仕様にするアプリケーションは少ないのでそういった実装を考えることはない」ということでしょうか？
→「クイズをタブで分けるようなアプリケーションはあまりない（クイズを分けるとしたらページ遷移で実装する）」ということでしょうか？
→「実際の現場ではデータベースにリストが保管されるので一概に言えないが、仮にリストを今回のようなオブジェクトや配列で記述する場合でもcategoriesのようなまとめ方は複雑になるのでせめて各クイズの配列を用意して実装することが一般的」ということでしょうか？

「実際の現場では」「一般的には」といったことではなく、やりたいこと（仕様）に対して、画面設計やデータの持ち方がチグハグになっているように見えたので、実装が難しくなっている、というようなイメージです

今回に関しては、実装部分だけでなんとか解決しようとすると、実装はより複雑になりアドバイス・質問などのやりとりも難易度が高まりそうだったので仕様や画面設計・データモデルの見直しが必要という判断をしてました

やりたいことが間違っている、一般的でない、といったことではないのでご安心を！！
あくまでも、実装を頑張るより先にアプローチを変える必要がある、という自分の考えですので🙏


余談ですが自分もエンジニアなりたてでReactを独学し始めた頃、ReactのチュートリアルやってからいきなりReactでオセロ作って非常に苦労していたことを思い出しました。。。
一人で詰まって気軽に相談できる相手もおらず数週間進捗でないこともあったり。。。

似たような状況だなぁと思うので、そういったところでも色々サポートできればと思っていますので今後ともよろしくお願いします🙌

Reactの学習を進めていく中でこのクイズアプリはどんどん質の高いアプリになっていく気がしています👍

**Comment by Mackie-S** [comment]
なるほど🤔
今回の部分、おっしゃるように実装部分をなんとか力技で乗り切ろうという思いは強かったと思います。
そういう時に発想というか切り口を変えて仕様、画面設計、データモデルの見直しが必要なんですね。。

みずしまさんも似たような状況があったんですね！
それでも今の状況があるのは試行錯誤して辞めずにやり続けた結果かと思うので私も勇気をもらえました😄

引き続きよろしくお願いいたします！！
